name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      
      - name: Check out code
        uses: actions/checkout@v3

      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      
      - name: Install Node.js dependencies
        run: |
          npm install
          npm run client:build

    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt

      
      - name: Run server tests
        run: |
          python -m unittest discover -s server/tests
