name: Checking Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Checking Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.x

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies and build
        run: |
          cd server
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
          cd ../client
          npm install
          npm run build

      - name: Run start
        run: |
          npm run client:build
          cd server
          python3 app.py
